#pragma once

#define ENABLE_MOTION 1

#define BALL_USE_RAW_DATA 1
#define ENABLE_CONTROLLER 0

#define ENABLE_COMMS_ROLE_CHANGE 1
#define ENABLE_BALL_ROLE_CHANGE_BACK 1

#define DEBUG_LED_LINE 1
#define DEBUG_LED_GOAL 1
#define DEBUG_LED_HASBALL 1
#define DEBUG_LED_FEATURES 0

#define DEBUG_LINE_RAW_RING 0
#define DEBUG_LINE_RAW_DEPTH 0

#define DEBUG_BALL 0
#define DEBUG_BALL_RAW 0

#define DEBUG_DISPLAY_LINE 0
#define DEBUG_DISPLAY_BALL 0
#define DEBUG_DISPLAY_FINAL_ANGLE 0


#define DEBUG_LINE_ANG 0
#define DEBUG_COMMs 0

#define DEBUG_CONTROLLER 0
#define DEBUG_BUKAJ_MODUL 0

#define DEBUG_PIXY_FRONT 0
#define DEBUG_PIXY_REAR 0
#define DEBUG_FINALANGLE 0

#define DEBUG_LINE_DEFENDER 0


#define DEFENDER_CHANGE_TO_ATTACKER 0
#define DEFENDER_KICK_TO_GOAL 1