[platformio]
default_envs = usb

[env:base]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 921600
upload_speed = 921600 

board_build.f_cpu = 240000000   ;240MHz
board_build.f_flash = 80000000  ;80MHz
board_build.flash_mode = qio

; board_upload.flash_size = 16MB
; board_upload.maximum_size = 16777216
; board_build.partitions = default_16MB.csv


board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv


board_build.psram = none

build_flags = 
  ; -O3 ;max optimalization
  -DBOARD_HAS_PSRAM=0
  -DCONFIG_SPIRAM_BOOT_INIT=0

[env:usb]
extends = env:base
upload_protocol = esptool

; [env:ota]
; extends = env:base
; upload_protocol = espota
; upload_port = 192.168.1.112
; upload_flags =
;   --port=3232
;   --host_ip=192.168.4.7
;   --host_port=55190
;   --timeout=30
